server:
  port: 8888
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: qja18344981008
    url: jdbc:mysql://localhost:3306/zhongchou?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mybatis/*Mapper.xml